[req]
default_bits = 2048
distinguished_name = dn
prompt             = no
req_extensions = req_ext

[dn]
countryName             = "US"
stateOrProvinceName     = "MI"
localityName            = "Detroit"
organizationName        = "Heavy Metal Cloud LLC"
organizationalUnitName  = "Devops"
commonName              = "heavymetalcloud.lan"

[req_ext]
subjectAltName = @alt_names

[alt_names]
DNS.1 = heavymetalcloud.lan
DNS.2 = *.heavymetalcloud.lan