customLdifFiles:
  00-root.ldif: |-
    #### Referenced from: https://www.zytrax.com/books/ldap/ch5/

    ## dcObject is an AUXILLIARY objectclass and MUST
    ## have a STRUCTURAL objectclass (organization in this case)
    # this is an ENTRY sequence and is preceded by a BLANK line

    dn: dc=heavymetalcloud,dc=lan
    dc: heavymetalcloud
    description: Heavy Metal Cloud, LLC is an organization for
      building light-weight cloud infrastructure at a client's data
      center or on premises.
    objectClass: dcObject
    objectClass: organization
    o: Heavy Metal Cloud, LLC
  01-people.ldif: |-
    ## FIRST Level hierarchy - people
    ## uses mixed upper and lower case for objectclass
    # this is an ENTRY sequence and is preceded by a BLANK line
    
    dn: ou=people, dc=heavymetalcloud,dc=lan
    ou: people
    description: All people in organisation
    objectclass: organizationalunit
    
    ## SECOND Level hierarchy
    ## ADD a single entry under FIRST (people) level
    # this is an ENTRY sequence and is preceded by a BLANK line
    # the ou: Human Resources is the department name
    
    dn: cn=Matt Metal,ou=people,dc=heavymetalcloud,dc=lan
    objectclass: inetOrgPerson
    cn: Matt Metal
    cn: Matt X. Metal
    cn: Matt Metal Nickname
    sn: metal
    uid: matt
    userpassword: password
    homephone: 555-111-2222
    mail: matt@heavymetalcloud.lan
    mail: matt.metal@heavymetalcloud.lan
    description: The Heavy Metal Cloud Guy
    ou: Information Technology
    
    dn: cn=Marla Metal,ou=people,dc=heavymetalcloud,dc=lan
    objectclass: inetOrgPerson
    cn: Marla Metal
    cn: Marla A. Metal
    sn: metal
    uid: marla
    userpassword: password
    homephone: 555-111-2222
    mail: marla@heavymetalcloud.lan
    mail: marla.metal@heavymetalcloud.lan
    description: A made up user
    ou: Account Team    
    
    dn: cn=Admin Metal,ou=people,dc=heavymetalcloud,dc=lan
    objectclass: inetOrgPerson
    cn: Admin Metal
    sn: metal
    uid: admin
    userpassword: password
    homephone: 555-111-2222
    mail: admin@heavymetalcloud.lan
    description: Admin
    ou: Administration
  02-group.ldif: |-
    ##### Groups
    # create FIRST Level groups branch
    
    dn: ou=groups,dc=heavymetalcloud,dc=lan
    objectclass: organizationalunit
    ou: groups
    description: generic groups branch
    
    # create the itpeople entry under groups
    
    dn: cn=itgroup,ou=groups,dc=heavymetalcloud,dc=lan
    objectclass: groupofnames
    cn: itgroup
    description: IT Group
    member: cn=Matt Metal,ou=people,dc=heavymetalcloud,dc=lan
    member: cn=Admin Metal,ou=people,dc=heavymetalcloud,dc=lan
    
    # create the Read Only entry under groups
    
    dn: cn=readonly,ou=groups,dc=heavymetalcloud,dc=lan
    objectclass: groupofnames
    cn: readonly
    description: Read Only group
    member: cn=Marla Metal,ou=people,dc=heavymetalcloud,dc=lan

### These are permissions to read/write etc. to the LDAP tree for a specific group
# REFERENCES:
## https://www.zytrax.com/books/ldap/ch5/step2.html
### https://github.com/jp-gouin/helm-openldap/issues/211#issuecomment-2435858080
### https://www.openldap.org/doc/admin24/access-control.html
customAcls: |-
  dn: olcDatabase={2}mdb,cn=config
  changetype: modify
  replace: olcAccess
  olcAccess: {0}to *
    by dn.exact=gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth manage
    by * break
  olcAccess: {1}to attrs=userPassword,shadowLastChange
    by self write
    by group.exact="cn=itgroup,ou=groups,dc=heavymetalcloud,dc=lan" write
    by anonymous auth by * none
  olcAccess: {2}to *
    by group.exact="cn=readonly,ou=groups,dc=heavymetalcloud,dc=lan" read
    by group.exact="cn=itgroup,ou=groups,dc=heavymetalcloud,dc=lan" write
    by dn="cn=Admin Metal,ou=people,dc=heavymetalcloud,dc=lan" manage
    by dn.children="ou=people,dc=heavymetalcloud,dc=lan" search
    by self read
    by * none